### **Carregamento e preparação dos dados**

In [40]:
# Importando as bibliotecas necessárias
import pandas as pd

In [41]:
# Carregando o arquivo CSV em um DataFrame
df = pd.read_csv('vw_olist_full.csv')

In [42]:
# Exibindo as informações do DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  object
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116601 non-null  object
 19  product_name_lenght            116601 non-null  float64
 20  product_description_lenght     116601 non-null  float64
 21  product_photos_qty             116601 non-null  float64
 22  product_weight_g               118290 non-null  float64
 23  product_length_cm              118290 non-null  float64
 24  product_height_cm              118290 non-null  float64
 25  product_width_cm               118290 non-null  float64
 26  seller_zip_code_prefix         118310 non-null  float64
 27  seller_city                    118310 non-null  object
 28  seller_state                   118310 non-null  object
 29  payment_sequential             119140 non-null  float64
 30  payment_type                   119140 non-null  object
 31  payment_installments           119140 non-null  float64
 32  payment_value                  119140 non-null  float64
 33  review_id                      118146 non-null  object
 34  review_score                   118146 non-null  float64
 35  review_comment_title           13989 non-null   object
 36  review_comment_message         50245 non-null   object
 37  review_creation_date           118146 non-null  object
 38  review_answer_timestamp        118146 non-null  object
dtypes: float64(15), int64(1), object(23)
memory usage: 35.5+ MB

In [43]:
# Exibindo uma amostra dos dados
df.sample(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
17151,24f6d178b92691453bffa42151277fbf,0b62558584ba5942cb07377647332e23,delivered,2018-08-06 16:31:57,2018-08-07 04:35:20,2018-08-08 12:05:00,2018-08-11 19:04:55,2018-08-21,c9aa33473ec2343d8a2a0b11ebd36b1d,8761,...,1.0,boleto,1.0,78.12,c4410b4871b11023a57a8b86d33522f0,3.0,NaN,Ainda não experimentei o produto por isso não ...,2018-08-12,2018-08-12 23:20:48
67809,9215daa2d711ae5055008f444f6688c8,8e9e8aa4d3d480bc21b3336de7eb9214,delivered,2018-01-14 19:00:30,2018-01-14 19:12:20,2018-01-16 13:57:05,2018-02-28 00:14:03,2018-02-09,d433955af3c49f3b58cac87cc0255ae9,23095,...,1.0,credit_card,4.0,64.00,d7ad3c494893c1c7afd933b1526bfc01,1.0,NaN,NaN,2018-02-11 00:00:00,2018-02-15 01:37:23
7206,0f7f3fcd5523d759e8e17084e45439d5,7e96ebdd045e73e50de71b8d1360b092,delivered,2017-07-20 19:24:24,2017-07-22 02:23:54,2017-07-25 19:36:34,2017-09-19 13:38:13,2017-08-23,02c56fe95ed4ef5fd0623142ffb83c28,59700,...,1.0,boleto,1.0,142.56,f16c56fc189cbfc13955753f1e135ae1,1.0,NaN,NaN,2017-08-27 00:00:00,2017-08-31 11:27:19
54448,74973f83083be040a56dfc7209f45fc8,c5223ed17c50a5c0c3f51a4b38b565f1,delivered,2018-07-20 15:25:04,2018-07-20 15:44:09,2018-07-23 11:24:00,2018-08-07 14:16:38,2018-08-08,d7ac1e2ab73bda5c3ed4ef3fb5ce27e5,36325,...,1.0,credit_card,2.0,193.30,9cc5a655f1bb96a9868214d39878bd78,3.0,NaN,NaN,2018-08-08 00:00:00,2018-08-08 17:38:52
104330,dfab4854076442f7a5a0e322ea7b6a5a,8b6f2427e98e7c98770f5edbf05e696d,delivered,2017-11-09 21:18:39,2017-11-11 14:10:34,2017-11-14 21:57:01,2017-11-21 18:58:53,2017-11-29,3dbd379ad1ac719a420c62b40867ff3e,11900,...,1.0,credit_card,1.0,27.98,cdf700f4d78878214351825d5475d615,1.0,NaN,NaN,2017-11-22,2017-11-23 00:08:08

In [44]:
# Corrigindo os tipos de dados de colunas de data

date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date",
    "review_creation_date",
    "review_answer_timestamp"    
]


for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [45]:
# Criando váriaveis agregadas.
df["entrega_atrasada"] = (df["order_delivered_customer_date"] > df["order_estimated_delivery_date"]).astype(int)
df["tempo_entrega_real"] = (df["order_delivered_customer_date"] - df["order_delivered_carrier_date"]).dt.days
df["tempo_entrega_estimado"] = (df["order_estimated_delivery_date"] - df["order_purchase_timestamp"]).dt.days

In [46]:
# Renomeando colunas para nomes mais curtos e intuitivos
df = df.rename(columns={
    "order_purchase_timestamp": "order_purchase_ts",
    "order_approved_at": "order_approved_ts",
    "order_delivered_carrier_date": "carrier_delivery_ts",
    "order_delivered_customer_date": "customer_delivery_ts",
    "order_estimated_delivery_date": "estimated_delivery_ts",
    "customer_zip_code_prefix": "customer_zip_prefix",
    "price": "item_price",
    "product_category_name": "product_category",
    "seller_zip_code_prefix": "seller_zip_prefix",
    "review_comment_title": "review_title",
    "review_comment_message": "review_message",
    "review_creation_date": "review_creation_ts",
    "review_answer_timestamp": "review_answer_ts"
    })

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 42 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   order_id                    119143 non-null  object
 1   customer_id                 119143 non-null  object
 2   order_status                119143 non-null  object
 3   order_purchase_ts           119143 non-null  datetime64[ns]
 4   order_approved_ts           118966 non-null  datetime64[ns]
 5   carrier_delivery_ts         117057 non-null  datetime64[ns]
 6   customer_delivery_ts        115722 non-null  datetime64[ns]
 7   estimated_delivery_ts       119143 non-null  datetime64[ns]
 8   customer_unique_id          119143 non-null  object
 9   customer_zip_prefix         119143 non-null  int64
 10  customer_city               119143 non-null  object
 11  customer_state              119143 non-null  object
 12  order_item_id               118310 non-null  float64
 13  product_id                  118310 non-null  object
 14  seller_id                   118310 non-null  object
 15  shipping_limit_date         118310 non-null  datetime64[ns]
 16  item_price                  118310 non-null  float64
 17  freight_value               118310 non-null  float64
 18  product_category            116601 non-null  object
 19  product_name_lenght         116601 non-null  float64
 20  product_description_lenght  116601 non-null  float64
 21  product_photos_qty          116601 non-null  float64
 22  product_weight_g            118290 non-null  float64
 23  product_length_cm           118290 non-null  float64
 24  product_height_cm           118290 non-null  float64
 25  product_width_cm            118290 non-null  float64
 26  seller_zip_prefix           118310 non-null  float64
 27  seller_city                 118310 non-null  object
 28  seller_state                118310 non-null  object
 29  payment_sequential          119140 non-null  float64
 30  payment_type                119140 non-null  object
 31  payment_installments        119140 non-null  float64
 32  payment_value               119140 non-null  float64
 33  review_id                   118146 non-null  object
 34  review_score                118146 non-null  float64
 35  review_title                13989 non-null   object
 36  review_message              50245 non-null   object
 37  review_creation_ts          91521 non-null   datetime64[ns]
 38  review_answer_ts            118146 non-null  datetime64[ns]
 39  entrega_atrasada            119143 non-null  int32
 40  tempo_entrega_real          115721 non-null  float64
 41  tempo_entrega_estimado      119143 non-null  int64
dtypes: datetime64[ns](8), float64(16), int32(1), int64(2), object(15)
memory usage: 37.7+ MB

In [48]:
df.sample(5)

,order_id,customer_id,order_status,order_purchase_ts,order_approved_ts,carrier_delivery_ts,customer_delivery_ts,estimated_delivery_ts,customer_unique_id,customer_zip_prefix,...,payment_value,review_id,review_score,review_title,review_message,review_creation_ts,review_answer_ts,entrega_atrasada,tempo_entrega_real,tempo_entrega_estimado
5072,0aed18a03ea2ccdb5981aea3524b304d,186d5e15485ff2afa04f02bd00aee4a4,delivered,2017-09-08 12:16:48,2017-09-12 04:55:21,2017-09-13 22:23:41,2017-09-23 01:23:34,2017-10-03,dc9108cdc59294eebe936e0971e6da63,60865,...,313.43,b1b8ed5013ee80279488d05cd327e154,1.0,NaN,Pedi duas cubas so recebi uma estou aguardando...,2017-09-23,2017-09-24 15:50:34,0,9.0,24
96658,cf48dd7cb04dee070d71d4804cac6272,1ce48e2220cceaec2d73107d3deafc55,delivered,2017-09-11 16:48:06,2017-09-11 18:04:49,2017-09-12 19:22:20,2017-09-24 12:29:54,2017-10-02,2db03deff30a590441f2e5f5175797b8,40295,...,70.50,472a6c2af834307ba71f5edd63e9cf95,5.0,NaN,NaN,2017-09-25,2017-09-26 16:36:59,0,11.0,20
67666,91c96626f9e13b1b71a1f3e7ed52dd7a,45442979a333bc62efccd8a2481481fe,delivered,2016-10-08 21:04:27,2016-10-09 02:33:03,2016-10-13 02:33:03,2016-10-26 14:33:48,2016-12-14,78712b57b1b1c000eec8434d73a7e37e,51030,...,102.69,040001387dba8164e025b9e919adc29b,5.0,NaN,"Muito bom vendedor, produto chegou antes do pr...",2016-10-27,2016-10-31 00:54:26,0,13.0,66
41820,59798edc300f7563a9bdf18b2740def9,be1abfd06882c0ee1d45b976da59a494,unavailable,2017-07-05 19:06:19,2017-07-05 19:23:18,NaT,NaT,2017-07-27,e8e76b99c4deb6dd66ace26de01e426b,32641,...,30.00,cad6c561173f86ccbb18cba27d7d0a50,1.0,NaN,NaN,2017-07-29,2017-07-31 19:44:40,0,NaN,21
27760,3b842ff9ea0324f7726503cadd3c0db5,26982dd51b55e2a5cd7793d84a0787c8,delivered,2018-08-07 08:53:33,2018-08-09 03:44:56,2018-08-10 11:53:00,2018-08-24 17:08:34,2018-09-04,fbb12b94afcf31408ac7820ec30e78d1,63800,...,198.05,27ee3ed83aa2e944fe7a148aeb20059d,5.0,Bom,Recomendo a compra nessa loja.,2018-08-25,2018-08-27 20:47:49,0,14.0,27

### **Métricas Principais (KPIs)**

In [49]:
# --- KPI 1: Taxa de pedidos atrasados ---
taxa_atraso = df['entrega_atrasada'].mean()
# --- KPI 2: Atraso médio em dias ---
df['dif_real_estimado'] = df['tempo_entrega_real'] - df['tempo_entrega_estimado']
atraso_medio = df['dif_real_estimado'].mean()
# --- KPI 3: Tempo médio de entrega real ---
tempo_real_medio = df['tempo_entrega_real'].mean()
# --- KPI 4: Tempo médio estimado ---
tempo_estimado_medio = df['tempo_entrega_estimado'].mean()
# --- KPI 5: Diferença real - estimado ---
erro_estimativa = df['dif_real_estimado'].mean()

In [50]:
# Exibir tudo organizado
kpis = {
    "Taxa de atraso (%)": round(taxa_atraso * 100, 2),
    "Atraso médio (dias)": round(atraso_medio, 2),
    "Tempo médio de entrega real (dias)": round(tempo_real_medio, 2),
    "Tempo médio estimado (dias)": round(tempo_estimado_medio, 2),
    "Erro médio da estimativa (dias)": round(erro_estimativa, 2)
}

kpis

{'Taxa de atraso (%)': 7.61,
 'Atraso médio (dias)': -14.73,
 'Tempo médio de entrega real (dias)': 8.75,
 'Tempo médio estimado (dias)': 23.5,
 'Erro médio da estimativa (dias)': -14.73}

``“A Olist entrega rápido, mas promete prazos excessivamente longos. Ajustar esse cálculo pode aumentar a conversão e a satisfação.”``

### **Análise por Seller (Proxy de Transportadora)**

In [52]:
# Taxa de atraso por seller
atraso_por_seller = (df.groupby("seller_id")["entrega_atrasada"].mean().sort_values(ascending=False).reset_index())
atraso_por_seller.rename(columns={"entrega_atrasada": "taxa_atraso"}, inplace=True)
atraso_por_seller

                             seller_id  taxa_atraso
0     6d04126aba80df143fd038e711b8fd96          1.0
1     da2782c804606d2a5d8e1760dbb3e7ec          1.0
2     2a73cba571d90c694b7caca072ccf6ce          1.0
3     c13ef0cfbe42f190780f621ce81f2234          1.0
4     bc8c8d665ec4664d286be0d521722b19          1.0
...                                ...          ...
3090  6b9b80d53ba3676eafe60268a810b5a1          0.0
3091  6b89abe95848c850399130d149a39b63          0.0
3092  6b803197e03abd5056b4313306b4f29d          0.0
3093  6b2612338467c08c9b25f0cc55b1578d          0.0
3094  ffff564a4f9085cd26170f4732393726          0.0

[3095 rows x 2 columns]

In [53]:
# Atraso médio em dias por seller (somente pedidos que atrasaram)
atraso_medio_seller = (df[df["entrega_atrasada"] == 1].groupby("seller_id")["tempo_entrega_real"].mean().sort_values(ascending=False).reset_index())
atraso_medio_seller.rename(columns={"tempo_entrega_real": "atraso_medio_dias"}, inplace=True)
atraso_medio_seller

                             seller_id  atraso_medio_dias
0     e83c76265fc54bf41eac728805e4da77              187.0
1     df683dfda87bf71ac3fc63063fba369d              186.0
2     1782ce2db72c3dda627d5e7c898104e1              169.0
3     4fb41dff7c50136976d1a5cf004a42e2              162.0
4     e81e1f9c3e762e620f3fb60a51499e16              122.0
...                                ...                ...
1385  244b04680fdbded0acf5aebd9c92b44a                0.0
1386  0692610d8abe24f287e9fae90ea0bbee                0.0
1387  1099a00e0ee3a50935e6c2447ca090c5                0.0
1388  9b522ba7eae9e1d04082f267144583cc                0.0
1389  3f2af2670e104d1bcb54022274daeac5                NaN

[1390 rows x 2 columns]

In [59]:
# Unir tudo em uma tabela final
seller_metrics = atraso_por_seller.merge(atraso_medio_seller, on="seller_id", how="left")

seller_metrics

                             seller_id  taxa_atraso  atraso_medio_dias
0     6d04126aba80df143fd038e711b8fd96          1.0                4.0
1     da2782c804606d2a5d8e1760dbb3e7ec          1.0               23.0
2     2a73cba571d90c694b7caca072ccf6ce          1.0                9.0
3     c13ef0cfbe42f190780f621ce81f2234          1.0                9.0
4     bc8c8d665ec4664d286be0d521722b19          1.0                1.0
...                                ...          ...                ...
3090  6b9b80d53ba3676eafe60268a810b5a1          0.0                NaN
3091  6b89abe95848c850399130d149a39b63          0.0                NaN
3092  6b803197e03abd5056b4313306b4f29d          0.0                NaN
3093  6b2612338467c08c9b25f0cc55b1578d          0.0                NaN
3094  ffff564a4f9085cd26170f4732393726          0.0                NaN

[3095 rows x 3 columns]

### **Relação entre atraso e review score**

In [ ]:
# Score médio por atraso vs não atraso
score_atraso = df.groupby('entrega_atrasada')['review_score'].mean().reset_index()
score_atraso['entrega_atrasada'] = score_atraso['entrega_atrasada'].map({0: 'No prazo', 1: 'Atrasado'})
score_atraso

  entrega_atrasada  review_score
0         No prazo      4.134724
1         Atrasado      2.546542

In [ ]:
# Distribuição de notas por atraso
dist_scores = df.groupby(['entrega_atrasada', 'review_score'])['order_id'].count().reset_index()
dist_scores.rename(columns={'order_id': 'qtde'}, inplace=True)
dist_scores

   entrega_atrasada  review_score   qtde
0                 0           1.0  11272
1                 0           2.0   3469
2                 0           3.0   8914
3                 0           4.0  21237
4                 0           5.0  64391
5                 1           1.0   4156
6                 1           2.0    693
7                 1           3.0    980
8                 1           4.0   1082
9                 1           5.0   1952

In [ ]:
# Probabilidade de nota 1 quando há atraso
prob_nota1 = (df[df['review_score'] == 1].groupby('entrega_atrasada')['order_id'].count() / df.groupby('entrega_atrasada')['order_id'].count()).reset_index()

prob_nota1.rename(columns={'order_id': 'prob_nota1'}, inplace=True)
prob_nota1

   entrega_atrasada  prob_nota1
0                 0    0.102403
1                 1    0.458315

``“Atrasos têm impacto direto e massivo na satisfação.Pedidos atrasados recebem nota 1 quase metade das vezes, puxando o score geral para baixo. A melhoria na logística pode reduzir drasticamente avaliações negativas.”``

### **Correlações e “drivers” do atraso**

In [ ]:
# Atraso médio e taxa de atraso por estado
df['customer_state'] = df['customer_state'].astype(str)

atraso_por_estado = (df.groupby('customer_state').agg(taxa_atraso=('entrega_atrasada', 'mean'),atraso_medio_dias=('tempo_entrega_real', 'mean')).reset_index().sort_values('taxa_atraso', ascending=False))

atraso_por_estado

   customer_state  taxa_atraso  atraso_medio_dias
1              AL     0.234914          20.510112
9              MA     0.193925          17.342649
16             PI     0.152778          15.637184
24             SE     0.151365          17.316062
5              CE     0.144409          17.022606
4              BA     0.132730          15.365570
18             RJ     0.124758          11.383135
13             PA     0.119575          19.810392
7              ES     0.119068          11.779983
19             RN     0.113240          15.417407
14             PB     0.111801          16.500000
26             TO     0.111765          13.143713
11             MS     0.104408          11.846698
15             PE     0.098636          14.514674
21             RR     0.096154          24.152174
23             SC     0.093211          11.100000
8              GO     0.076237          11.817537
6              DF     0.071145           9.214548
22             RS     0.066180          11.462053
12             MT     0.062721          14.368762
25             SP     0.054869           5.074309
10             MG     0.052319           8.238720
3              AP     0.047619          24.048193
17             PR     0.046500           8.205633
2              AM     0.040462          23.258824
20             RO     0.037671          16.387900
0              AC     0.031579          16.840426

In [ ]:
# Atraso por peso do produto
atraso_por_peso = (df.groupby(pd.qcut(df['product_weight_g'], 6)).agg(taxa_atraso=('entrega_atrasada', 'mean'),atraso_medio=('tempo_entrega_real', 'mean')).reset_index())

atraso_por_peso.head()

C:\Users\cassi\AppData\Local\Temp\ipykernel_13156\3540303348.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  atraso_por_peso = (df.groupby(pd.qcut(df['product_weight_g'], 6)).agg(taxa_atraso=('entrega_atrasada', 'mean'),atraso_medio=('tempo_entrega_real', 'mean')).reset_index())

   product_weight_g  taxa_atraso  atraso_medio
0   (-0.001, 200.0]     0.071016      8.013507
1    (200.0, 400.0]     0.076593      8.522724
2    (400.0, 700.0]     0.070561      8.648989
3   (700.0, 1350.0]     0.076145      8.831464
4  (1350.0, 3050.0]     0.080582      9.231768

In [ ]:
# Correlação com variáveis contínuas
cols_continuas = [
    'freight_value', 'product_weight_g',
    'product_length_cm', 'product_height_cm', 'product_width_cm',
    'tempo_entrega_estimado', 'tempo_entrega_real'
]

correlacoes = df[cols_continuas + ['entrega_atrasada']].corr()['entrega_atrasada'].sort_values(ascending=False)
correlacoes

entrega_atrasada          1.000000
tempo_entrega_real        0.548383
freight_value             0.038677
product_weight_g          0.021818
product_length_cm         0.013874
product_height_cm         0.010424
product_width_cm          0.003880
tempo_entrega_estimado   -0.061971
Name: entrega_atrasada, dtype: float64

In [ ]:
# Sellers mais problemáticos
sellers_ruins = ( df.groupby('seller_id').agg(taxa_atraso=('entrega_atrasada', 'mean'),atraso_medio=('tempo_entrega_real', 'mean'),num_pedidos=('seller_id', 'count')).query("num_pedidos >= 20").sort_values('taxa_atraso', ascending=False).head(10))

sellers_ruins

                                  taxa_atraso  atraso_medio  num_pedidos
seller_id
2709af9587499e95e803a6498a5a56e9     0.479167      9.127660           48
f76a3b1349b6df1ee875d1f3fa4340f0     0.400000      7.920000           25
835f0f7810c76831d6c7d24c7a646d4d     0.351852      9.403846           54
973f21788dfab357250f69a8dcb7ddee     0.333333      9.526316           21
ede0c03645598cdfc63ca8237acbe73d     0.320000     14.106383           50
54965bbe3e4f07ae045b90b0b8541f52     0.306818     10.301205           88
821fb029fc6e495ca4f08a35d51e53a5     0.300000     13.807692           30
7f152321c60a266edc53af1925ef96c1     0.300000     19.100000           20
2a1348e9addc1af5aaa619b1a3679d6b     0.272727     21.549020           55
054694fa03fe82cec4b7551487331d74     0.272727     19.476190           22